### ISSUE TITLE
Why ban the localhost

### ISSUE THREAD

**Issue by klren0312** [MystenLabs/wallet_blocklist#1]
when I develop the page in local, visit http://localhost:3000, the wallet throw the error Malicious website

![image](https://github.com/user-attachments/assets/6fb3dfe1-6662-400f-bbf7-b4b1fdb9d696)
I don't think this is necessary
![image](https://github.com/user-attachments/assets/5809b191-973c-483b-9e0a-66e29c1b66a0)

**Comment by maxmysten** [comment]
Bug, fixing now

**Comment by maxmysten** [comment]
Fixed and added to whitelist
